[2025-05-14T05:15:31.637+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ecommerce_data_ingestion.wait_for_olist_order_customer_dataset manual__2025-05-14T05:13:11.949842+00:00 [queued]>
[2025-05-14T05:15:31.904+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ecommerce_data_ingestion.wait_for_olist_order_customer_dataset manual__2025-05-14T05:13:11.949842+00:00 [queued]>
[2025-05-14T05:15:31.910+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 3
[2025-05-14T05:15:32.380+0000] {taskinstance.py:2191} INFO - Executing <Task(FileSensor): wait_for_olist_order_customer_dataset> on 2025-05-14 05:13:11.949842+00:00
[2025-05-14T05:15:32.698+0000] {standard_task_runner.py:60} INFO - Started process 257 to run task
[2025-05-14T05:15:32.879+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'ecommerce_data_ingestion', 'wait_for_olist_order_customer_dataset', 'manual__2025-05-14T05:13:11.949842+00:00', '--job-id', '124', '--raw', '--subdir', 'DAGS_FOLDER/ecommerce_etl_dag.py', '--cfg-path', '/tmp/tmpj_cqcamk']
[2025-05-14T05:15:33.057+0000] {standard_task_runner.py:88} INFO - Job 124: Subtask wait_for_olist_order_customer_dataset
[2025-05-14T05:15:33.822+0000] {task_command.py:423} INFO - Running <TaskInstance: ecommerce_data_ingestion.wait_for_olist_order_customer_dataset manual__2025-05-14T05:13:11.949842+00:00 [running]> on host 1e43c0d7b523
[2025-05-14T05:15:34.399+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ecommerce_data_ingestion' AIRFLOW_CTX_TASK_ID='wait_for_olist_order_customer_dataset' AIRFLOW_CTX_EXECUTION_DATE='2025-05-14T05:13:11.949842+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-14T05:13:11.949842+00:00'
[2025-05-14T05:15:34.510+0000] {base.py:83} INFO - Using connection ID 'fs_default' for task execution.
[2025-05-14T05:15:34.525+0000] {filesystem.py:66} INFO - Poking for file /opt/***/data/extracted_data/olist_order_customer_dataset.csv
[2025-05-14T05:20:34.676+0000] {base.py:83} INFO - Using connection ID 'fs_default' for task execution.
[2025-05-14T05:20:34.686+0000] {filesystem.py:66} INFO - Poking for file /opt/***/data/extracted_data/olist_order_customer_dataset.csv
[2025-05-14T05:23:56.045+0000] {local_task_job_runner.py:302} WARNING - State of this instance has been externally set to removed. Terminating instance.
[2025-05-14T05:23:56.065+0000] {process_utils.py:131} INFO - Sending 15 to group 257. PIDs of all processes in the group: [257]
[2025-05-14T05:23:56.066+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 257
[2025-05-14T05:23:56.068+0000] {taskinstance.py:2450} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-05-14T05:23:56.168+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=257, status='terminated', exitcode=0, started='05:15:32') (257) terminated with exit code 0
