[2025-06-09T10:20:50.773+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kafka_ecommerce_pipeline.run_kafka_producer scheduled__2025-06-09T10:18:00+00:00 [queued]>
[2025-06-09T10:20:50.782+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kafka_ecommerce_pipeline.run_kafka_producer scheduled__2025-06-09T10:18:00+00:00 [queued]>
[2025-06-09T10:20:50.783+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 3
[2025-06-09T10:20:50.794+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): run_kafka_producer> on 2025-06-09 10:18:00+00:00
[2025-06-09T10:20:50.797+0000] {standard_task_runner.py:60} INFO - Started process 169 to run task
[2025-06-09T10:20:50.800+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'kafka_ecommerce_pipeline', 'run_kafka_producer', 'scheduled__2025-06-09T10:18:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/kafka_data_pipeline.py', '--cfg-path', '/tmp/tmp78j31ur3']
[2025-06-09T10:20:50.801+0000] {standard_task_runner.py:88} INFO - Job 6: Subtask run_kafka_producer
[2025-06-09T10:20:50.834+0000] {task_command.py:423} INFO - Running <TaskInstance: kafka_ecommerce_pipeline.run_kafka_producer scheduled__2025-06-09T10:18:00+00:00 [running]> on host a0ec9d43225f
[2025-06-09T10:20:50.912+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data-engineering-team' AIRFLOW_CTX_DAG_ID='kafka_ecommerce_pipeline' AIRFLOW_CTX_TASK_ID='run_kafka_producer' AIRFLOW_CTX_EXECUTION_DATE='2025-06-09T10:18:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-09T10:18:00+00:00'
[2025-06-09T10:20:50.914+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-06-09T10:20:50.915+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /app/producer.py']
[2025-06-09T10:20:50.924+0000] {subprocess.py:86} INFO - Output:
[2025-06-09T10:20:50.951+0000] {subprocess.py:93} INFO - python: can't open file '/app/producer.py': [Errno 2] No such file or directory
[2025-06-09T10:20:50.953+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2025-06-09T10:20:50.966+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 428, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-06-09T10:20:50.973+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=kafka_ecommerce_pipeline, task_id=run_kafka_producer, execution_date=20250609T101800, start_date=20250609T102050, end_date=20250609T102050
[2025-06-09T10:20:50.988+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 6 for task run_kafka_producer (Bash command failed. The command returned a non-zero exit code 2.; 169)
[2025-06-09T10:20:51.026+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-06-09T10:20:51.056+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
