[2025-06-07T10:53:55.963+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ingestion_dag.run_ingestion_script manual__2025-06-07T10:53:53.894472+00:00 [queued]>
[2025-06-07T10:53:55.977+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ingestion_dag.run_ingestion_script manual__2025-06-07T10:53:53.894472+00:00 [queued]>
[2025-06-07T10:53:55.977+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-06-07T10:53:55.989+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): run_ingestion_script> on 2025-06-07 10:53:53.894472+00:00
[2025-06-07T10:53:56.000+0000] {standard_task_runner.py:60} INFO - Started process 330 to run task
[2025-06-07T10:53:56.004+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'ingestion_dag', 'run_ingestion_script', 'manual__2025-06-07T10:53:53.894472+00:00', '--job-id', '30', '--raw', '--subdir', 'DAGS_FOLDER/ingestion_dag.py', '--cfg-path', '/tmp/tmpj5_dkgod']
[2025-06-07T10:53:56.008+0000] {standard_task_runner.py:88} INFO - Job 30: Subtask run_ingestion_script
[2025-06-07T10:53:56.070+0000] {task_command.py:423} INFO - Running <TaskInstance: ingestion_dag.run_ingestion_script manual__2025-06-07T10:53:53.894472+00:00 [running]> on host ab0825485965
[2025-06-07T10:53:56.131+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ingestion_dag' AIRFLOW_CTX_TASK_ID='run_ingestion_script' AIRFLOW_CTX_EXECUTION_DATE='2025-06-07T10:53:53.894472+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-07T10:53:53.894472+00:00'
[2025-06-07T10:53:56.135+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-06-07T10:53:56.139+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /opt/***/ingestion && python ingestion_script.py']
[2025-06-07T10:53:56.155+0000] {subprocess.py:86} INFO - Output:
[2025-06-07T10:53:57.166+0000] {subprocess.py:93} INFO - 2025-06-07 10:53:57,161 - data_ingestion - INFO - AWS_REGION: eu-north-1
[2025-06-07T10:53:57.173+0000] {subprocess.py:93} INFO - 2025-06-07 10:53:57,161 - data_ingestion - INFO - S3_BUCKET: rj-ecom-etl
[2025-06-07T10:53:57.175+0000] {subprocess.py:93} INFO - 2025-06-07 10:53:57,161 - data_ingestion - INFO - AWS_ACCESS_KEY_ID: ***
[2025-06-07T10:53:57.176+0000] {subprocess.py:93} INFO - 2025-06-07 10:53:57,161 - data_ingestion - INFO - AWS_SECRET_ACCESS_KEY: ***
[2025-06-07T10:53:57.176+0000] {subprocess.py:93} INFO - 2025-06-07 10:53:57,171 - data_ingestion - ERROR - Directory does not exist: /Users/rojan/Desktop/cp-project/e-commerce-analytics/data/extracted_data
[2025-06-07T10:53:57.283+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-06-07T10:53:57.326+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-06-07T10:53:57.340+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=ingestion_dag, task_id=run_ingestion_script, execution_date=20250607T105353, start_date=20250607T105355, end_date=20250607T105357
[2025-06-07T10:53:57.362+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 30 for task run_ingestion_script (Bash command failed. The command returned a non-zero exit code 1.; 330)
[2025-06-07T10:53:57.408+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-06-07T10:53:57.472+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
