[2025-06-08T10:00:04.268+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kafka_data_pipeline.run_kafka_consumer scheduled__2025-06-08T09:58:00+00:00 [queued]>
[2025-06-08T10:00:04.273+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kafka_data_pipeline.run_kafka_consumer scheduled__2025-06-08T09:58:00+00:00 [queued]>
[2025-06-08T10:00:04.274+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-06-08T10:00:04.280+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): run_kafka_consumer> on 2025-06-08 09:58:00+00:00
[2025-06-08T10:00:04.286+0000] {standard_task_runner.py:60} INFO - Started process 7676 to run task
[2025-06-08T10:00:04.291+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'kafka_data_pipeline', 'run_kafka_consumer', 'scheduled__2025-06-08T09:58:00+00:00', '--job-id', '325', '--raw', '--subdir', 'DAGS_FOLDER/kafka_data_pipeline.py', '--cfg-path', '/tmp/tmpn03l_qih']
[2025-06-08T10:00:04.292+0000] {standard_task_runner.py:88} INFO - Job 325: Subtask run_kafka_consumer
[2025-06-08T10:00:04.353+0000] {task_command.py:423} INFO - Running <TaskInstance: kafka_data_pipeline.run_kafka_consumer scheduled__2025-06-08T09:58:00+00:00 [running]> on host 677411ab3888
[2025-06-08T10:00:04.407+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='kafka_data_pipeline' AIRFLOW_CTX_TASK_ID='run_kafka_consumer' AIRFLOW_CTX_EXECUTION_DATE='2025-06-08T09:58:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-08T09:58:00+00:00'
[2025-06-08T10:00:04.409+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-06-08T10:00:04.410+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/ecom_etl/kafka_scripts/consumer.py']
[2025-06-08T10:00:04.418+0000] {subprocess.py:86} INFO - Output:
[2025-06-08T10:00:06.676+0000] {subprocess.py:93} INFO - Error: NoBrokersAvailable
[2025-06-08T10:00:06.742+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-06-08T10:00:06.769+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=kafka_data_pipeline, task_id=run_kafka_consumer, execution_date=20250608T095800, start_date=20250608T100004, end_date=20250608T100006
[2025-06-08T10:00:06.788+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-06-08T10:00:06.805+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
