[2025-06-08T15:59:21.390+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kafka_data_pipeline.run_kafka_consumer manual__2025-06-08T15:59:13.860222+00:00 [queued]>
[2025-06-08T15:59:21.400+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kafka_data_pipeline.run_kafka_consumer manual__2025-06-08T15:59:13.860222+00:00 [queued]>
[2025-06-08T15:59:21.403+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-06-08T15:59:21.412+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): run_kafka_consumer> on 2025-06-08 15:59:13.860222+00:00
[2025-06-08T15:59:21.417+0000] {standard_task_runner.py:60} INFO - Started process 536 to run task
[2025-06-08T15:59:21.420+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'kafka_data_pipeline', 'run_kafka_consumer', 'manual__2025-06-08T15:59:13.860222+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/kafka_data_pipeline.py', '--cfg-path', '/tmp/tmpbv6yww_6']
[2025-06-08T15:59:21.422+0000] {standard_task_runner.py:88} INFO - Job 5: Subtask run_kafka_consumer
[2025-06-08T15:59:21.465+0000] {task_command.py:423} INFO - Running <TaskInstance: kafka_data_pipeline.run_kafka_consumer manual__2025-06-08T15:59:13.860222+00:00 [running]> on host aece8d7c74c6
[2025-06-08T15:59:21.512+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='kafka_data_pipeline' AIRFLOW_CTX_TASK_ID='run_kafka_consumer' AIRFLOW_CTX_EXECUTION_DATE='2025-06-08T15:59:13.860222+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-08T15:59:13.860222+00:00'
[2025-06-08T15:59:21.514+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-06-08T15:59:21.515+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/ecom_etl/kafka_scripts/consumer.py']
[2025-06-08T15:59:21.530+0000] {subprocess.py:86} INFO - Output:
[2025-06-08T15:59:21.793+0000] {subprocess.py:93} INFO - 2025-06-08 15:59:21,792 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-06-08T15:59:21.794+0000] {subprocess.py:93} INFO - 2025-06-08 15:59:21,793 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T15:59:21.795+0000] {subprocess.py:93} INFO - 2025-06-08 15:59:21,793 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T15:59:21.796+0000] {subprocess.py:93} INFO - 2025-06-08 15:59:21,793 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-06-08T15:59:21.796+0000] {subprocess.py:93} INFO - 2025-06-08 15:59:21,793 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T15:59:21.796+0000] {subprocess.py:93} INFO - 2025-06-08 15:59:21,793 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T15:59:21.797+0000] {subprocess.py:93} INFO - 2025-06-08 15:59:21,793 - kafka.client - WARNING - No node available during check_version; sleeping 0.04 secs
[2025-06-08T15:59:21.836+0000] {subprocess.py:93} INFO - 2025-06-08 15:59:21,835 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-06-08T15:59:21.836+0000] {subprocess.py:93} INFO - 2025-06-08 15:59:21,835 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T15:59:21.836+0000] {subprocess.py:93} INFO - 2025-06-08 15:59:21,835 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T15:59:21.837+0000] {subprocess.py:93} INFO - 2025-06-08 15:59:21,835 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-06-08T15:59:21.837+0000] {subprocess.py:93} INFO - 2025-06-08 15:59:21,836 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T15:59:21.837+0000] {subprocess.py:93} INFO - 2025-06-08 15:59:21,836 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T15:59:21.837+0000] {subprocess.py:93} INFO - 2025-06-08 15:59:21,836 - kafka.client - WARNING - No node available during check_version; sleeping 0.12 secs
[2025-06-08T15:59:21.955+0000] {subprocess.py:93} INFO - 2025-06-08 15:59:21,955 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-06-08T15:59:21.956+0000] {subprocess.py:93} INFO - 2025-06-08 15:59:21,955 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T15:59:21.956+0000] {subprocess.py:93} INFO - 2025-06-08 15:59:21,955 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T15:59:21.956+0000] {subprocess.py:93} INFO - 2025-06-08 15:59:21,955 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-06-08T15:59:21.956+0000] {subprocess.py:93} INFO - 2025-06-08 15:59:21,955 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T15:59:21.956+0000] {subprocess.py:93} INFO - 2025-06-08 15:59:21,955 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T15:59:21.956+0000] {subprocess.py:93} INFO - 2025-06-08 15:59:21,955 - kafka.client - WARNING - No node available during check_version; sleeping 0.17 secs
[2025-06-08T15:59:22.125+0000] {subprocess.py:93} INFO - 2025-06-08 15:59:22,124 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-06-08T15:59:22.127+0000] {subprocess.py:93} INFO - 2025-06-08 15:59:22,125 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T15:59:22.128+0000] {subprocess.py:93} INFO - 2025-06-08 15:59:22,125 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T15:59:22.128+0000] {subprocess.py:93} INFO - 2025-06-08 15:59:22,126 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-06-08T15:59:22.129+0000] {subprocess.py:93} INFO - 2025-06-08 15:59:22,127 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T15:59:22.129+0000] {subprocess.py:93} INFO - 2025-06-08 15:59:22,127 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T15:59:22.130+0000] {subprocess.py:93} INFO - 2025-06-08 15:59:22,127 - kafka.client - WARNING - No node available during check_version; sleeping 0.41 secs
[2025-06-08T15:59:22.540+0000] {subprocess.py:93} INFO - 2025-06-08 15:59:22,539 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-06-08T15:59:22.541+0000] {subprocess.py:93} INFO - 2025-06-08 15:59:22,540 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T15:59:22.542+0000] {subprocess.py:93} INFO - 2025-06-08 15:59:22,540 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T15:59:22.542+0000] {subprocess.py:93} INFO - 2025-06-08 15:59:22,540 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-06-08T15:59:22.542+0000] {subprocess.py:93} INFO - 2025-06-08 15:59:22,541 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T15:59:22.543+0000] {subprocess.py:93} INFO - 2025-06-08 15:59:22,541 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T15:59:22.543+0000] {subprocess.py:93} INFO - 2025-06-08 15:59:22,541 - kafka.client - WARNING - No node available during check_version; sleeping 0.89 secs
[2025-06-08T15:59:23.434+0000] {subprocess.py:93} INFO - 2025-06-08 15:59:23,433 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-06-08T15:59:23.436+0000] {subprocess.py:93} INFO - 2025-06-08 15:59:23,435 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T15:59:23.437+0000] {subprocess.py:93} INFO - 2025-06-08 15:59:23,436 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T15:59:23.438+0000] {subprocess.py:93} INFO - 2025-06-08 15:59:23,436 - kafka.conn - INFO - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-06-08T15:59:23.438+0000] {subprocess.py:93} INFO - 2025-06-08 15:59:23,437 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 111. Disconnecting.
[2025-06-08T15:59:23.438+0000] {subprocess.py:93} INFO - 2025-06-08 15:59:23,437 - kafka.conn - ERROR - <BrokerConnection client_id=kafka-python-2.2.11, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-06-08T15:59:23.439+0000] {subprocess.py:93} INFO - 2025-06-08 15:59:23,437 - kafka.client - WARNING - No node available during check_version; sleeping 0.35 secs
[2025-06-08T15:59:23.800+0000] {subprocess.py:93} INFO - Error: NoBrokersAvailable
[2025-06-08T15:59:23.921+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-06-08T15:59:23.965+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=kafka_data_pipeline, task_id=run_kafka_consumer, execution_date=20250608T155913, start_date=20250608T155921, end_date=20250608T155923
[2025-06-08T15:59:24.006+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-06-08T15:59:24.029+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
