[2025-06-08T04:33:20.364+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kafka_data_pipeline.run_kafka_producer manual__2025-06-08T04:32:17.532859+00:00 [queued]>
[2025-06-08T04:33:20.378+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kafka_data_pipeline.run_kafka_producer manual__2025-06-08T04:32:17.532859+00:00 [queued]>
[2025-06-08T04:33:20.379+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 2
[2025-06-08T04:33:20.395+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): run_kafka_producer> on 2025-06-08 04:32:17.532859+00:00
[2025-06-08T04:33:20.406+0000] {standard_task_runner.py:60} INFO - Started process 118 to run task
[2025-06-08T04:33:20.412+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'kafka_data_pipeline', 'run_kafka_producer', 'manual__2025-06-08T04:32:17.532859+00:00', '--job-id', '77', '--raw', '--subdir', 'DAGS_FOLDER/kafka_data_pipeline.py', '--cfg-path', '/tmp/tmps1i5uldn']
[2025-06-08T04:33:20.413+0000] {standard_task_runner.py:88} INFO - Job 77: Subtask run_kafka_producer
[2025-06-08T04:33:20.463+0000] {task_command.py:423} INFO - Running <TaskInstance: kafka_data_pipeline.run_kafka_producer manual__2025-06-08T04:32:17.532859+00:00 [running]> on host 4f027a4ee08e
[2025-06-08T04:33:20.512+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='kafka_data_pipeline' AIRFLOW_CTX_TASK_ID='run_kafka_producer' AIRFLOW_CTX_EXECUTION_DATE='2025-06-08T04:32:17.532859+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-08T04:32:17.532859+00:00'
[2025-06-08T04:33:20.513+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-06-08T04:33:20.514+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/ecom_etl/kafka_scripts/producer.py']
[2025-06-08T04:33:20.522+0000] {subprocess.py:86} INFO - Output:
[2025-06-08T04:33:20.577+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-06-08T04:33:20.578+0000] {subprocess.py:93} INFO -   File "/opt/***/ecom_etl/kafka_scripts/producer.py", line 11, in <module>
[2025-06-08T04:33:20.578+0000] {subprocess.py:93} INFO -     from kafka import KafkaProducer
[2025-06-08T04:33:20.579+0000] {subprocess.py:93} INFO - ModuleNotFoundError: No module named 'kafka'
[2025-06-08T04:33:20.581+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-06-08T04:33:20.589+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-06-08T04:33:20.595+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=kafka_data_pipeline, task_id=run_kafka_producer, execution_date=20250608T043217, start_date=20250608T043320, end_date=20250608T043320
[2025-06-08T04:33:20.607+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 77 for task run_kafka_producer (Bash command failed. The command returned a non-zero exit code 1.; 118)
[2025-06-08T04:33:20.634+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-06-08T04:33:20.661+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
